# Site settings
title: ND Insurance Agency
email: ndagencyllc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "natalliad.github.io" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
